id: AA5255443
title: 'The Hook of Compassion: Calling the Guru from Afar'
type: translation
pechas:
- I77A89C44
- I1A6D89D9
- I343A4934
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:00:39.457541
  last_modified_at: 2023-01-04 12:00:39.457550
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I77A89C44/AD66: '1964'
  I1A6D89D9/927E: '1964'
  I343A4934/4562: '1964'
